import { ApolloServer } from "@apollo/server";
import { startServerAndCreateNextHandler } from "@as-integrations/next";
import { unstable_getServerSession } from "next-auth";
import "reflect-metadata";
import { buildSchemaSync } from "type-graphql";
import {
  BookmarkCrudResolver,
  BookmarkRelationsResolver,
  CollectionCrudResolver,
  ExternalServiceCredentialRelationsResolver,
  TagCrudResolver,
  TagRelationsResolver,
  UserRelationsResolver,
} from "../../lib/graphql/server/generated";
import { container } from "../../server/container";
import { IContext } from "../../server/context";
import { IContextProvider } from "../../server/context/ContextProvider";

import {
  CollectionRelationsResolver,
  ExternalServiceResolver,
  UserResolver,
} from "../../server/resolvers";
import { CustomCollectionResolver } from "../../server/resolvers/CustomCollectionResolver";
import { PrismaService } from "../../server/services/PrismaService";
import { authOptions } from "./auth/[...nextauth]";

// Tells Next.js that we don't want it to parse the request body
export const config = {
  api: {
    bodyParser: false,
  },
};

// @ts-ignore - resolved via Next.js webpack override
export const schema = buildSchemaSync({
  resolvers: [
    BookmarkCrudResolver,
    BookmarkRelationsResolver,
    UserResolver,
    TagCrudResolver,
    CollectionCrudResolver,
    CustomCollectionResolver,
    CollectionRelationsResolver,
    TagRelationsResolver,
    UserRelationsResolver,
    ExternalServiceResolver,
    ExternalServiceCredentialRelationsResolver,
  ],
});

const apolloServer = new ApolloServer<IContext>({ schema });

export default startServerAndCreateNextHandler(apolloServer, {
  context: async (req, res) => {
    return {
      req,
      res,
      session: await unstable_getServerSession(req, res, authOptions),
      container: container.get<IContextProvider>(
        Symbol.for("IContextProvider")
      ),
      // Need to include prisma in context for autogenerated resolvers
      prisma: container.get<PrismaService>(PrismaService),
    };
  },
});
